name: basic_landing_with_get
description: "A Flutter project for basic frame. Just for saving time"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6 #State management
  auto_size_text: ^3.0.0 #Control text size auto fit it's container
  awesome_dialog: ^3.2.1 #Build popup dialog
  flutter_easyloading: ^3.0.5 #Loading animation
  shared_preferences: ^2.2.3 #Local data control
  dio: ^5.7.0 #Network request
  logger: ^2.4.0 #Log
  fpdart: ^1.1.0 #Functional programming

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
